exodus/analysis_query/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'analysis'
urlpatterns = [
    path('', views.AnalysisRequestListView.as_view(), name='index'),
    path('submit/', views.AnalysisRequestView.as_view(), name='submit'),
    path('<int:r_id>/', views.wait, name='wait'),
    path('<int:r_id>/json/', views.json, name='json'),
]

if settings.ALLOW_APK_UPLOAD:
    urlpatterns.append(path('upload/', views.upload_file, name='upload'))

exodus/exodus/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/', include('restful_api.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += i18n_patterns(
    path('', views.index, name='home'),
    path('analysis/', include('analysis_query.urls')),
    path('trackers/', include('trackers.urls')),
    path('reports/', include('reports.urls')),
    path('info/permissions/', views.permissions, name='permissions'),
    path('info/trackers/', views.trackers, name='trackers'),
    path('info/next/', views.next, name='next'),
    path('info/understand/', views.understand, name='understand'),
    path('info/organization/', views.organization, name='organization'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = 'exodus.views.page_not_found'
# handler500 = 'exodus.views.page_not_found'

exodus/reports/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.get_reports, name='list'),
    path('<int:report_id>/', views.detail, name='detail'),
    path('<int:app_id>/icon/', views.get_app_icon, name='icon'),
    path('stats/', RedirectView.as_view(pattern_name='trackers:get_stats', permanent=False)),
    path('search/<handle>/', views.get_reports, name='search_by_handle'),
    path('<handle>/latest/', views.detail, name='get_latest'),
    path('<handle>/latest/icon/', views.get_app_icon, name='icon_by_handle'),
]

exodus/trackers/urls.py
from django.urls import path

from . import views

app_name = 'trackers'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:tracker_id>/', views.detail, name='detail'),
    path('stats/', views.get_stats, name='get_stats'),
    path('graph/', views.graph, name='graph'),
    path('details/', views.TrackersListView.as_view(), name='all_details'),
    path('api_key/', views.new_api_key, name='new_api_key'),
]

exodus/reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from minio import Minio
from minio.error import (ResponseError, NoSuchBucket)

from django.utils import translation
from trackers.models import Tracker
from exodus.core.permissions_en import AOSP_PERMISSIONS_EN
from exodus.core.permissions_fr import AOSP_PERMISSIONS_FR

AOSP_PERMISSIONS = {
    'en': AOSP_PERMISSIONS_EN,
    'fr': AOSP_PERMISSIONS_FR
}


class Report(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    found_trackers = models.ManyToManyField(Tracker)
    storage_path = models.CharField(max_length=200, default='')
    bucket = models.CharField(max_length=200, default='')
    apk_file = models.CharField(max_length=200, default='')
    pcap_file = models.CharField(max_length=200, default='')
    flow_file = models.CharField(max_length=200, default='')
    class_list_file = models.CharField(max_length=200, default='')

    def __str__(self):
        try:
            handle = self.application.handle
        except Exception:
            handle = "<malformed report>"
        return handle

    def trackers(self):
        return self.found_trackers.order_by('name')


def _get_color_class(count):
    if count == 0:
        color_class = "success"
    elif count < 5:
        color_class = "warning"
    else:
        color_class = "danger"
    return color_class


class Application(models.Model):
    report = models.OneToOneField(Report, on_delete=models.CASCADE)
    handle = models.CharField(max_length=200)
    name = models.CharField(max_length=200, default='')
    creator = models.CharField(max_length=200, default='')
    downloads = models.CharField(max_length=200, default='')
    version = models.CharField(max_length=50)
    version_code = models.CharField(max_length=100, default='')
    icon_path = models.CharField(max_length=500, default='')
    app_uid = models.CharField(max_length=128, default='')
    icon_phash = models.CharField(max_length=128, default='')
    source = models.CharField(max_length=50, default='')

    def __str__(self):
        return self.handle

    def trackers_class(self):
        return _get_color_class(self.trackers_count())

    def permissions_class(self):
        return _get_color_class(self.permissions_count())

    def trackers_count(self):
        return len(self.report.found_trackers.all())

    def permissions_count(self):
        return len(self.permission_set.all())

    def permissions(self):
        return self.permission_set.all().order_by('name')

    def count_dangerous_permissions(self):
        perms = self.permissions()
        count = 0
        for p in perms:
            if p.severity == "Dangerous":
                count += 1
        return count

    def count_special_permissions(self):
        perms = self.permissions()
        count = 0
        for p in perms:
            if p.severity == "Special":
                count += 1
        return count

    @property
    def json_signature(self):
        sign = {
            'handle': self.handle,
            'uaid': self.app_uid,
            'sha256sum': self.apk.sum,
            'name': self.name,
            'version': self.version,
            'version_code': self.version_code,
            'icon_hash': self.icon_phash,
        }
        return json.dumps(sign, indent=2)


class Apk(models.Model):
    application = models.OneToOneField(Application, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    sum = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Certificate(models.Model):
    apk = models.ForeignKey(Apk, on_delete=models.CASCADE)
    has_expired = models.BooleanField(default=False)
    serial_number = models.CharField(max_length=128, default='')
    issuer = models.CharField(max_length=500, default='')
    subject = models.CharField(max_length=500, default='')
    fingerprint = models.CharField(max_length=256, default='')

    def __str__(self):
        return self.fingerprint


class Permission(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

    def get_permission_details(self):
        language = translation.get_language()
        if language not in AOSP_PERMISSIONS.keys():
            language = "en"
        aosp_data = AOSP_PERMISSIONS[language]
        permissions = aosp_data["permissions"]
        perm = permissions.get(self.name, {})
        return perm

    def get_group_details(self):
        language = translation.get_language()
        if language not in AOSP_PERMISSIONS.keys():
            language = "en"
        aosp_data = AOSP_PERMISSIONS[language]
        groups = aosp_data["groups"]
        group = groups.get(self.group, {})
        return group

    @property
    def short_name(self):
        return str(self.name).split('.')[-1]

    @property
    def prefix(self):
        return '.'.join(str(self.name).split('.')[:-1])

    @property
    def protection_level(self):
        perm = self.get_permission_details()
        protection_level = perm.get("protection_level", "Unknown")
        return protection_level

    @property
    def severity(self):
        # These permissions are defined as "special permissions" by Google
        SPECIAL_PERMISSIONS = [
            "SYSTEM_ALERT_WINDOW",
            "WRITE_SETTINGS"
        ]
        if self.short_name in SPECIAL_PERMISSIONS:
            return "Special"

        protection_level = self.protection_level
        if "dangerous" in protection_level:
            return "Dangerous"
        elif protection_level == "Unknown":
            return "Unknown"
        else:
            return "Normal"

    @property
    def description(self):
        perm = self.get_permission_details()
        description = perm.get("description", "")
        return description

    @property
    def label(self):
        perm = self.get_permission_details()
        label = perm.get("label", "")
        return label

    @property
    def group(self):
        perm = self.get_permission_details()
        group = perm.get("permission_group", "")
        return group

    @property
    def group_icon(self):
        group = self.get_group_details()
        icon = group.get("icon", "")
        return icon


@receiver(post_delete, sender=Report, dispatch_uid='report_delete_signal')
def remove_report_files(sender, instance, using, **kwargs):
    minio_client = Minio(settings.MINIO_STORAGE_ENDPOINT,
                         access_key=settings.MINIO_STORAGE_ACCESS_KEY,
                         secret_key=settings.MINIO_STORAGE_SECRET_KEY,
                         secure=settings.MINIO_STORAGE_USE_HTTPS)
    try:
        objects = minio_client.list_objects(settings.MINIO_STORAGE_MEDIA_BUCKET_NAME,
                                            prefix=instance.bucket,
                                            recursive=True)
        for obj in objects:
            minio_client.remove_object(settings.MINIO_STORAGE_MEDIA_BUCKET_NAME, obj.object_name)
    except ResponseError as err:
        print(err)
    except NoSuchBucket as err:
        print(err)

exodus/reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from django.conf import settings
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from minio import Minio

from reports.models import Report, Application


def index(request):
    return render(request, 'reports_home.html')


def get_reports(request, handle=None):
    filter = request.GET.get('filter', None)
    try:
        if filter == 'no_trackers':
            reports = Report.objects.filter(found_trackers=None).order_by('-creation_date')
        elif filter == 'most_trackers':
            reports = Report.objects.exclude(found_trackers=None).annotate(nb_trackers=Count('found_trackers')).order_by('-nb_trackers')
        else:
            reports = Report.objects.order_by('-creation_date')
            if handle:
                reports = reports.filter(application__handle=handle)
    except Report.DoesNotExist:
        raise Http404(_("Report does not exist"))

    reports_number = reports.count()

    paginator = Paginator(reports, settings.EX_PAGINATOR_COUNT)
    reports = paginator.get_page(request.GET.get('page'))

    return render(
        request, 'reports_list.html',
        {
            'reports': reports,
            'reports_count': reports_number,
            'reports_total_count': Report.objects.count(),
            'apps_total_count': Application.objects.distinct('handle').count(),
            'filter': filter,
            'handle': handle
        }
    )


def detail(request, report_id=None, handle=None):
    try:
        report = None
        if report_id:
            report = Report.objects.get(pk=report_id)
        elif handle:
            report = Report.objects.filter(application__handle=handle).order_by('-creation_date').first()
        if report is None:
            raise Report.DoesNotExist
    except Report.DoesNotExist:
        raise Http404(_("Report does not exist"))

    return render(request, 'report_details.html', {'report': report})


def get_app_icon(request, app_id=None, handle=None):
    try:
        app = None
        if app_id:
            app = Application.objects.get(pk=app_id)
        elif handle:
            app = Application.objects.filter(handle=handle).order_by('-report__creation_date').first()
        if app is None:
            raise Application.DoesNotExist
    except Application.DoesNotExist:
        raise Http404(_('App does not exist'))

    minioClient = Minio(
        settings.MINIO_STORAGE_ENDPOINT,
        access_key=settings.MINIO_STORAGE_ACCESS_KEY,
        secret_key=settings.MINIO_STORAGE_SECRET_KEY,
        secure=settings.MINIO_STORAGE_USE_HTTPS
    )

    try:
        data = minioClient.get_object(settings.MINIO_STORAGE_MEDIA_BUCKET_NAME, app.icon_path)
        return HttpResponse(data.data, content_type='image/png')
    except Exception as err:
        print(err)
        with open(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'android.jpeg'), 'rb') as f:
            return HttpResponse(f.read(), content_type='image/jpeg')

exodus/reports/templates/admin_change_list.html
{% extends "admin/change_list.html" %}
{% load static %}

<!-- Override extrahead to add Chart.js -->
{% block extrahead %}
{{ block.super }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
  const ctx = document.getElementById('myChart').getContext('2d');

  const chartData = {{ chart_data | safe }};

  // Parse the dates to JS
  chartData.forEach((d) => {
    d.x = new Date(d.date);
  });

  // Render the chart
  const chart = new Chart(ctx, {
    type: 'bar',
    data: {
      datasets: [
        {
          label: 'new elements',
          data: chartData,
          backgroundColor: 'rgba(220,20,20,0.5)',
        },
      ],
    },
    options: {
      responsive: true,
      scales: {
        xAxes: [
          {
            type: 'time',
            time: {
              unit: 'month',
              round: 'month',
              displayFormats: {
                month: 'MMM Y',
              },
            },
          },
        ],
        yAxes: [
          {
            ticks: {
              beginAtZero: true,
            },
          },
        ],
      },
    },
  });
});
</script>
{% endblock %}

{% block content %}
<!-- Render our chart -->
<div style="width: 80%;">
  <canvas style="margin-bottom: 30px; width: 60%; height: 50%;" id="myChart"></canvas>
</div>
<!-- Render the rest of the ChangeList view -->
{{ block.super }}
{% endblock %}

exodus/reports/templates/report_details.html
{% extends "base/base.html"%}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
  {% load static %}
  {% if report %}
    {% if request.user.is_superuser %}
      <p class="small alert alert-warning">
        <samp>/api/report/{{ report.id }}/</samp>
        <br>
        {% trans "Prefix in storage:" %}
        <samp>{{ report.bucket }}</samp>
      </p>
    {% endif %}

    <div class="row justify-content-sm-center">
      <div class="col-xl-2 col-lg-2 col-md-8 col-12 text-lg-left text-center mb-4">
        <img src="/{{ LANGUAGE_CODE }}/reports/{{ report.application.id }}/icon/" class="rounded" width="115" height="115" alt="{{ report.application.handle }} logo">
      </div>
      <div class="col-xl-6 col-lg-6 col-md-8 col-12 text-center text-lg-left my-auto mb-4">
        <h1 class="main-title">
          {% if report.application.name.strip %}{{ report.application.name }}{% else %}{{ report.application.handle }}{% endif %}
        </h1>
      </div>
    </div>

    <div class="row justify-content-sm-center">
      <div class="col-md-8 col-lg-4 col-12 mb-4">
        <h3>
          <a href="#trackers" class="section-link">
            <span class="badge badge-pill badge-{{ report.application.trackers_class }} reports">{{ report.found_trackers.count }}</span>
            <b>{% blocktrans count count=report.found_trackers.count %}tracker{% plural %}trackers{% endblocktrans %}</b>
          </a>
        </h3>
      </div>
      <div class="col-md-8 col-lg-4 col-12 mb-4">
        <h3>
          <a href="#permissions" class="section-link">
            <span class="badge badge-pill badge-{{ report.application.permissions_class }} reports">{{ report.application.permission_set.count }}</span>
            <b>{% blocktrans count count=report.application.permission_set.count %}permission{% plural %}permissions{% endblocktrans %}</b>
          </a>
        </h3>
      </div>
    </div>

    <div class="row justify-content-sm-center mb-5">
      <div class="col-md-8 col-12">
        {% if report.application.version.strip %}
          {% trans "Version" %} {{ report.application.version }} -
          <a href="/reports/search/{{ report.application.handle }}">{% trans "see other versions" %}</a>
          <br>
        {% endif %}
        {% if report.application.source %}
          {% trans "Source:" %}
          {% if report.application.source == 'google' %}
            Google Play
          {% elif report.application.source == 'fdroid' %}
            F-Droid
          {% else %}
            {{ report.application.source }}
          {% endif %}
          <br>
        {% endif %}
        {% if report.application.creator.strip %}
          {% trans "Created by" %} {{ report.application.creator }}
          <br>
        {% endif %}
        {% if report.application.downloads.strip %}
          {% trans "Downloads:" %} {{ report.application.downloads | cut:' downloads' }}
          <br>
        {% endif %}
        <span class="text-muted">
          {% trans "Report created on" %} {{ report.creation_date }}
          {% if report.creation_date.date != report.updated_at.date %}
            {% trans "and updated on" %} {{ report.updated_at }}
          {% endif %}
        </span>
      </div>
      {% if request.user.is_superuser %}
        <div class="col-md-8 col-12 mt-2">
          <a type="button" class="btn btn-secondary" href="{% url 'analysis:submit' %}#{{ report.application.handle }}">{% trans "New analysis" %}</a>
          <a type="button" class="btn btn-danger" href="{% url 'admin:reports_report_delete' report.id %}">{% trans "Delete this report" %}</a>
        </div>
      {% endif %}
      <div class="col-md-8 col-12 text-right mt-2">
        {% if report.application.source and report.application.source == 'fdroid' %}
          <a class="link main-link" target="_blank" rel="noreferrer" href="https://f-droid.org/packages/{{ report.application.handle }}">{% trans "See on F-Droid" %}</a>
        {% else %}
          <a class="link main-link" target="_blank" rel="noreferrer" href="https://play.google.com/store/apps/details?id={{ report.application.handle }}">{% trans "See on Google Play" %}</a>
        {% endif %}
      </div>
    </div>

    <div class="row justify-content-sm-center mb-5">
      <div class="col-md-8 col-12">
        <a class="anchor" id="trackers"></a>
        <h3>
          <span class="badge badge-pill badge-{{ report.application.trackers_class }} reports">{{ report.found_trackers.count }}</span>
          <b>{% blocktrans count count=report.found_trackers.count %}tracker{% plural %}trackers{% endblocktrans %}</b>
        </h3>
      </div>
      <div class="col-md-8 col-12">
        {% if report.found_trackers.all %}
          <p>
            {% blocktrans trimmed count counter=report.found_trackers.count %}
              We have found <b>code signature</b> of the following tracker in the application:
            {% plural %}
              We have found <b>code signature</b> of the following trackers in the application:
            {% endblocktrans %}
          </p>
          {% for t in report.trackers %}
            <p class="mb-0"><a class="link black" href="{% url 'trackers:detail' t.id %}">{{ t.name }}</a></p>
            <p>
              {% for c in t.category.all %}
                <span class="badge badge-pill badge-outline-primary">{{ c | lower }}</span>
              {% endfor %}
            </p>
          {% endfor %}
        {% else %}
          <p>
            {% trans "We have not found <b>code signature</b> of any tracker we know in the application." %}
            <br>
            {% trans "The application could contain tracker(s) we do not know yet." %}
          </p>
        {% endif %}
        {% trans "A tracker is a piece of software meant to collect data about you or your usages." %}
        <a href="{% url 'trackers' %}">{% trans "Learn more" %}...</a>
      </div>
    </div>

    <div class="row justify-content-sm-center mb-5">
      <div class="col-md-8 col-12">
        <a class="anchor" id="permissions"></a>
        <h3>
          <span class="badge badge-pill badge-{{ report.application.permissions_class }} reports">{{ report.application.permission_set.count }}</span>
          <b>{% blocktrans count count=report.application.permission_set.count %}permission{% plural %}permissions{% endblocktrans %}</b>
        </h3>
      </div>
      <div class="col-md-8 col-12">
        {% if report.application.permission_set.all %}
          <p>
            {% blocktrans trimmed count counter=report.application.permission_set.count %}
              We have found the following permission in the application:
            {% plural %}
              We have found the following permissions in the application:
            {% endblocktrans %}
          </p>
          {% for perm in report.application.permissions %}
            <p class="text-truncate">
              {% if perm.group_icon %}
                {% autoescape off %}{{ perm.group_icon }}{% endautoescape %}
              {% else %}
                <span class="p-l-28px" </span>
              {% endif %}
              {% if perm.severity == 'Special' or perm.severity == 'Dangerous' %}
                &nbsp;<img  data-toggle="tooltip" data-placement="top" title="Protection level: {{ perm.protection_level }}" src="/static/img/danger.svg">&nbsp;
              {% endif %}
              <span data-toggle="tooltip" data-placement="top" title="{{ perm.prefix }}.{{ perm.short_name }}">{{ perm.short_name }}</span>
              {% if perm.label %}
                <small class="d-block p-l-28px"><i>{{ perm.label }}</i></small>
              {% endif %}
            </p>
          {% endfor %}
          <p>
            <small class="text-muted font-italic">
              {% blocktrans trimmed %}
                The icon &nbsp;<img src="/static/img/danger.svg">&nbsp; indicates a 'Dangerous' or 'Special' level according to <a target="_blank" rel="noreferrer" href="https://developer.android.com/guide/topics/permissions/overview">Google's protection levels</a>.
              {% endblocktrans %}
            </small>
          </p>
        {% else %}
          <p>{% trans "This application doesn't require any permissions." %}</p>
        {% endif %}
        {% trans "Permissions are actions the application can do on your phone." %}
        <a href="{% url 'permissions' %}">{% trans "Learn more" %}...</a>
      </div>
    </div>

    <div class="row justify-content-sm-center mb-4">
      <div class="col-md-8 col-12">
        <h4>{% trans "What's next?" %}</h4>
        {% trans "If this application does not sufficiently respect your privacy in your opinion, some alternatives exist!" %}
      </div>
    </div>

    <div class="row justify-content-center mb-5">
      <div class="col-md-3 col-6 text-center">
        <a href="{% url 'next' %}" class="btn btn-primary btn-block">{% trans "Read the article" %}</a>
      </div>
    </div>

    <div class="row justify-content-sm-center mb-5">
      <div class="col-md-8 col-12">
        {% trans "This report lists trackers signatures found by static analysis in this APK. This is not a proof of activity of these trackers." %}
        <br>
        <br>
        {% trans "The application could contain tracker(s) we do not know yet." %}
        <br>
        {% trans "If you have doubts about this report" %}, <a href="{% url 'organization' %}">{% trans "contact us" %}</a>.
      </div>
    </div>

    <div class="row justify-content-sm-center mb-4">
      <div class="col-md-8 col-12">
        <h4>{% trans "Signed by" %}</h4>
        {% if report.application.apk.certificate_set.all %}
          <small>
            {% for c in report.application.apk.certificate_set.all %}
              <p><b>{% trans "Fingerprint:" %}</b> <samp>{{ c.fingerprint }}</samp></p>
              <p><b>{% trans "Issuer:" %}</b> <samp>{{ c.issuer }}</samp></p>
              <p><b>{% trans "Subject:" %}</b> <samp>{{ c.subject }}</samp></p>
              <p><b>{% trans "Serial:" %}</b> <samp>{{ c.serial_number }}</samp></p>
            {% endfor %}
          </small>
        {% else %}
          {% trans "No signatures found <b>OR</b> x509 certificate does not comply the RFC." %}
        {% endif %}
      </div>
      <div class="col-md-8 col-12">
        <div class="btn-group">
          <button type="button" class="btn btn-primary btn-sm dropdown-toggle" id="dropdownApkFingerprint" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans "See APK fingerprint" %}
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownApkFingerprint">
            <a class="dropdown-item" data-toggle="modal" href="#collapseAPKDetails" aria-expanded="false" aria-controls="collapseAPKDetails">{% trans "Text" %}</a>
            <a class="dropdown-item" data-toggle="modal" href="#collapseAPKDetailsJSON" aria-expanded="false" aria-controls="collapseAPKDetailsJSON">JSON</a>
          </div>
        </div>
        <div class="modal fade" id="collapseAPKDetails" tabindex="-1" role="dialog" aria-labelledby="collapseAPKDetails" aria-hidden="true">
          <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">{% trans "APK fingerprint" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body">
                <ul class="list-unstyled">
                  <li><b>{% trans "APK checksum:" %}</b> <samp>{{ report.application.apk.sum }}</samp></li>
                  <li><b>{% trans "Handle:" %}</b> <samp>{{ report.application.handle }}</samp></li>
                  <li><b>{% trans "Name:" %}</b> <samp>{{ report.application.name }}</samp></li>
                  <li><b>{% trans "UAID:" %}</b> <samp>{{ report.application.app_uid }}</samp></li>
                  <li><b>{% trans "Version:" %}</b> <samp>{{ report.application.version }}</samp></li>
                  <li><b>{% trans "Version code:" %}</b> <samp>{{ report.application.version_code }}</samp></li>
                  <li><b>{% trans "Icon hash:" %}</b> <samp>{{ report.application.icon_phash }}</samp></li>
                </ul>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="collapseAPKDetailsJSON" tabindex="-1" role="dialog" aria-labelledby="collapseAPKDetailsJSON" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">{% trans "APK fingerprint" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body">
                      <pre><code>{{ report.application.json_signature }}</code></pre>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

exodus/reports/templates/reports_by_trackers.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <div class="row justify-content-md-center">
        <div class="alert alert-warning">
            <div class="alert-heading">
                <h4><span class="badge badge-info">{{ reports.count}}</span> Available report{{ reports.count|pluralize }} for these trackers</h4>
            </div>
            <table style="margin: auto; border:none" class="table table-hover">
                {% for report in reports %}
                <tr>
                    <td>
                        <a href="{% url 'reports:detail' report.id %}">
                            <img  data-toggle="tooltip" title="{{ report.application.handle }}" src="/reports/{{report.application.id}}/icon" width="30px" class="figure-img img-fluid rounded" alt="{{app.handle}}">
                            {% if report.application.name.strip %}
                                <b>{{ report.application.name }}</b>
                            {% else %}
                                <b>{{ report.application.handle }}</b>
                            {% endif %}
                        </a>
                    </td>
                    <td>
                        <span class="small"><b>{{ report.application.version }}</b></span>
                    </td>
                    <td>
                        <span class="small"><b>{{ report.creation_date }}</b></span>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

exodus/reports/templates/reports_home.html
{% extends "base/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
  {% load static %}
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-centered">
      <div class="text-center">
        <h1 class="main-title">
          {% trans "Reports" %}
        </h1>
      </div>
    </div>
  </div>

  {% include "snippets/reports_search.html" %}

  {% include "snippets/reports_links.html" %}

  {% include "snippets/reports_search_tpl.html" %}
{% endblock %}